export const CITIES = [
	{ key: 'Ho Chi Minh', label: 'Ho Chi Minh City' },
	{ key: 'Da Nang', label: 'Da Nang City' },
	{ key: 'Ha Noi', label: 'Ha Noi City' },
];

export const DISTRICTS = {
	'Ho Chi Minh': [
		{ key: 'quan1', label: 'District 1' },
		{ key: 'quan2', label: 'District 2' },
		{ key: 'quan3', label: 'District 3' },
		{ key: 'quan4', label: 'District 4' },
		{ key: 'quan5', label: 'District 5' },
		{ key: 'quan6', label: 'District 6' },
		{ key: 'quan7', label: 'District 7' },
		{ key: 'quan8', label: 'District 8' },
		{ key: 'quan9', label: 'District 9' },
		{ key: 'quan10', label: 'District 10' },
		{ key: 'quan11', label: 'District 11' },
		{ key: 'quan12', label: 'District 12' },
		{ key: 'thuduc', label: 'Thu Duc City' },
		{ key: 'binhtan', label: 'Binh Tan District' },
		{ key: 'tanbinh', label: 'Tan Binh District' },
		{ key: 'tanphu', label: 'Tan Phu District' },
		{ key: 'phunhuan', label: 'Phu Nhuan District' },
		{ key: 'binhthanh', label: 'Binh Thanh District' },
		{ key: 'govap', label: 'Go Vap District' },
		{ key: 'hocmon', label: 'Hoc Mon District' },
		{ key: 'binhchanh', label: 'Binh Chanh District' },
		{ key: 'cuchi', label: 'Cu Chi District' },
		{ key: 'nhabe', label: 'Nha Be District' },
		{ key: 'cangio', label: 'Can Gio District' },
	],

	'Da Nang': [
		{ key: 'sontra', label: 'Son Tra District' },
		{ key: 'hoavang', label: 'Hoa Vang District' },
		{ key: 'camle', label: 'Cam Le District' },
		{ key: 'nguhanhson', label: 'Ngu Hanh Son District' },
		{ key: 'lienchieu', label: 'Lien Chieu District' },
		{ key: 'thanhkhe', label: 'Thanh Khe District' },
	],

	'Ha Noi': [
		{ key: 'hoankiem', label: 'Hoan Kiem District' },
		{ key: 'badinh', label: 'Ba Dinh District' },
		{ key: 'dongda', label: 'Dong Da District' },
		{ key: 'haibatrung', label: 'Hai Ba Trung District' },
		{ key: 'tayho', label: 'Tay Ho District' },
		{ key: 'longbien', label: 'Long Bien District' },
		{ key: 'caugiay', label: 'Cau Giay District' },
		{ key: 'hoangmai', label: 'Hoang Mai District' },
		{ key: 'sontay', label: 'Son Tay District' },
		{ key: 'donganh', label: 'Dong Anh District' },
		{ key: 'melinh', label: 'Me Linh District' },
		{ key: 'gialam', label: 'Gia Lam District' },
		{ key: 'thanhtri', label: 'Thanh Tri District' },
		{ key: 'phuxuyen', label: 'Phu Xuyen District' },
		{ key: 'thachthat', label: 'Thach That District' },
	],
};

export const WARDS = {
	district1: {
		label: 'District 1',
		wards: [
			'Ben Nghe',
			'Ben Thanh',
			'Cau Kho',
			'Cau Ong Lanh',
			'Nguyen Cu Trinh',
			'Nguyen Thai Binh',
			'Pham Ngu Lao',
		],
	},
	district2: {
		label: 'District 2',
		wards: [
			'Thao Dien',
			'An Phu',
			'An Khanh',
			'Binh Trung Tay',
			'Binh Trung Dong',
			'Thanh My Loi',
			'Cat Lai',
		],
	},
	district3: {
		label: 'District 3',
		wards: [
			'Ward 1',
			'Ward 2',
			'Ward 3',
			'Ward 4',
			'Ward 5',
			'Ward 6',
			'Ward 7',
			'Ward 8',
			'Ward 9',
			'Ward 10',
		],
	},
	district4: {
		label: 'District 4',
		wards: [
			'Ward 1',
			'Ward 2',
			'Ward 3',
			'Ward 4',
			'Ward 6',
			'Ward 8',
			'Ward 9',
			'Ward 10',
			'Ward 12',
			'Ward 13',
			'Ward 14',
		],
	},
	district5: {
		label: 'District 5',
		wards: [
			'Ward 1',
			'Ward 2',
			'Ward 3',
			'Ward 4',
			'Ward 5',
			'Ward 6',
			'Ward 7',
			'Ward 8',
			'Ward 9',
			'Ward 10',
			'Ward 11',
			'Ward 12',
			'Ward 13',
		],
	},
	district6: {
		label: 'District 6',
		wards: [
			'Ward 1',
			'Ward 2',
			'Ward 3',
			'Ward 4',
			'Ward 5',
			'Ward 6',
			'Ward 7',
			'Ward 8',
			'Ward 9',
			'Ward 10',
			'Ward 11',
			'Ward 12',
		],
	},
	district7: {
		label: 'District 7',
		wards: [
			'Tan Thuan Dong',
			'Tan Thuan Tay',
			'Binh Thuan',
			'Phu Thuan',
			'Tan Kieng',
			'Tan Quy',
			'Tan Phong',
			'Tan Hung',
		],
	},
	district8: {
		label: 'District 8',
		wards: [
			'Ward 1',
			'Ward 2',
			'Ward 3',
			'Ward 4',
			'Ward 5',
			'Ward 6',
			'Ward 7',
			'Ward 8',
			'Ward 9',
			'Ward 10',
			'Ward 11',
			'Ward 12',
			'Ward 13',
		],
	},
	district9: {
		label: 'District 9',
		wards: [
			'Long Binh',
			'Long Thanh My',
			'Tan Phu',
			'Hiep Phu',
			'Tang Nhon Phu A',
			'Tang Nhon Phu B',
			'Phuoc Long A',
			'Phuoc Long B',
		],
	},
	district10: {
		label: 'District 10',
		wards: [
			'Ward 1',
			'Ward 2',
			'Ward 3',
			'Ward 4',
			'Ward 5',
			'Ward 6',
			'Ward 7',
			'Ward 8',
			'Ward 9',
			'Ward 10',
			'Ward 11',
			'Ward 12',
		],
	},
	district11: {
		label: 'District 11',
		wards: [
			'Ward 1',
			'Ward 2',
			'Ward 3',
			'Ward 4',
			'Ward 5',
			'Ward 6',
			'Ward 7',
			'Ward 8',
			'Ward 9',
			'Ward 10',
			'Ward 11',
			'Ward 12',
			'Ward 13',
			'Ward 14',
			'Ward 15',
			'Ward 16',
		],
	},
	district12: {
		label: 'District 12',
		wards: [
			'Thanh Loc',
			'Thanh Xuan',
			'Thoi An',
			'Hiep Thanh',
			'Tan Chanh Hiep',
			'Trung My Tay',
			'Tan Hung Thuan',
			'An Phu Dong',
		],
	},
	thuduc: {
		label: 'Thu Duc',
		wards: [
			'Linh Trung',
			'Linh Xuan',
			'Hiep Binh Chanh',
			'Hiep Binh Phuoc',
			'Truong Tho',
			'Linh Tay',
			'Linh Chieu',
		],
	},
	binhtan: {
		label: 'Binh Tan',
		wards: [
			'An Lac',
			'An Lac A',
			'Binh Hung Hoa',
			'Binh Hung Hoa A',
			'Binh Hung Hoa B',
			'Binh Tri Dong',
			'Binh Tri Dong A',
			'Tan Tao',
			'Tan Tao A',
		],
	},
	tanbinh: {
		label: 'Tan Binh',
		wards: [
			'Ward 1',
			'Ward 2',
			'Ward 3',
			'Ward 4',
			'Ward 5',
			'Ward 6',
			'Ward 7',
			'Ward 8',
			'Ward 9',
			'Ward 10',
			'Ward 11',
			'Ward 12',
		],
	},
	tanphu: {
		label: 'Tan Phu',
		wards: [
			'Phu Thanh',
			'Phu Tho Hoa',
			'Phu Trung',
			'Son Ky',
			'Tan Quy',
			'Tan Son Nhi',
			'Tan Thanh',
			'Tan Thoi Hoa',
		],
	},
	phunhuan: {
		label: 'Phu Nhuan',
		wards: [
			'Ward 1',
			'Ward 2',
			'Ward 3',
			'Ward 4',
			'Ward 5',
			'Ward 6',
			'Ward 7',
			'Ward 8',
			'Ward 9',
			'Ward 10',
			'Ward 11',
		],
	},
	binhthanh: {
		label: 'Binh Thanh',
		wards: [
			'Ward 1',
			'Ward 2',
			'Ward 3',
			'Ward 5',
			'Ward 6',
			'Ward 7',
			'Ward 11',
			'Ward 12',
		],
	},
	govap: {
		label: 'Go Vap',
		wards: [
			'Ward 1',
			'Ward 2',
			'Ward 3',
			'Ward 4',
			'Ward 5',
			'Ward 6',
			'Ward 7',
			'Ward 8',
			'Ward 9',
			'Ward 10',
			'Ward 11',
		],
	},
	hocmon: {
		label: 'Hoc Mon',
		wards: [
			'Xuan Thoi Son',
			'Xuan Thoi Thuong',
			'Tan Hiep',
			'Tan Thoi Nhi',
		],
	},
	binhchanh: {
		label: 'Binh Chanh',
		wards: [
			'Pham Van Hai',
			'Vinh Loc A',
			'Vinh Loc B',
			'Binh Hung',
			'Tan Quy Tay',
		],
	},
	cuchi: {
		label: 'Cu Chi',
		wards: ['Phu My Hung', 'Tan Thong Hoi', 'Trung Lap Ha'],
	},
	nhabe: {
		label: 'Nha Be',
		wards: ['Hiep Phuoc', 'Nhon Duc', 'Phuoc Kien', 'Phu Xuan'],
	},
	cangio: {
		label: 'Can Gio',
		wards: ['Long Hoa', 'An Thoi Dong', 'Tam Thon Hiep', 'Ly Nhon'],
	},
};
