import type { Metadata } from 'next';
import '../../styles/globals.css';
import { NavigationBar } from '../../components/NavigationBar';
import { Background } from '../../components/Background';

export const metadata: Metadata = {
	title: 'Match Mates',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<Background>
			<NavigationBar>{children}</NavigationBar>
		</Background>
	);
}
