/* eslint-disable @next/next/no-page-custom-font */
import type { Metadata } from 'next';
import '../../styles/globals.css';
import MobileChecking from '../../components/MobileChecking';
import { NextUIProvider } from '@nextui-org/react';
import { NavigationBar } from '../../components/NavigationBar';

export const metadata: Metadata = {
	title: 'Match Mates',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<head>
				<link
					rel='preconnect'
					href='https://fonts.googleapis.com'
				/>
				<link
					rel='preconnect'
					href='https://fonts.gstatic.com'
					crossOrigin=''
				/>
				<link
					href='https://fonts.googleapis.com/css2?family=Bagel+Fat+One&family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap'
					rel='stylesheet'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui'
				/>
			</head>
			<body>
				<NextUIProvider>
					<MobileChecking>
						<NavigationBar>{children}</NavigationBar>
					</MobileChecking>
				</NextUIProvider>
			</body>
		</html>
	);
}
